# Generated by Django 5.2.17 on 2026-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeroleaudit',
            name='from_role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employeeroleaudit',
            name='to_role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='employeeroleaudit',
            name='action',
            field=models.CharField(choices=[('grant', 'Выдана'), ('revoke', 'Отозвана'), ('change', 'Изменена')], max_length=8),
        ),
    ]
