# Generated by Django 5.2.16 on 2026-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(default='order.created', max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('published', 'Отправлено')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_orde_status_01745b_idx')],
            },
        ),
    ]
