# Generated by Django 5.2.16 on 2026-09-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderoutbox_snapshot_run_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(unique=True)),
                ('request_event_id', models.UUIDField()),
                ('correlation_id', models.UUIDField()),
                ('outcome_event_id', models.UUIDField(unique=True)),
                ('outcome_type', models.CharField(max_length=64)),
                ('outcome_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderoutbox',
            name='causation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
