# Generated by Django 5.2.16 on 2026-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_commandinbox_orderoutbox_causation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoutbox',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
