# Generated by Django 5.2.17 on 2026-09-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_outbox_lease_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('published', 'Отправлено'), ('failed', 'Снято оператором')], db_index=True, default='pending', max_length=12),
        ),
    ]
