global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    project: asian-restaurant

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: operations-consumer
    metrics_path: /metrics
    static_configs:
      - targets: ["operations-consumer:9101"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
