# Generated by Django 5.2.17 on 2026-09-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_outbox_failed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeauthorization',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
