# Generated by Django 5.2.17 on 2026-09-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_employee_authorization_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeauthorization',
            name='roles_known',
            field=models.BooleanField(default=False),
        ),
    ]
